name: Push-to-EC2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Buid API
      run: |
        npm ci --prefix api &&
        npm run build --prefix api &&
        cp api/node_modules api/build &&
        ls api

    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: api/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: api/build

      - name: Deploy in EC2
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: |
              -----BEGIN OPENSSH PRIVATE KEY-----
              b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz
              c2gtZWQyNTUxOQAAACBrgceIWXbgY2l03WOaKkn4B8vhQJcXDcVGXnZjev+WZAAA
              AIhL6MPkS+jD5AAAAAtzc2gtZWQyNTUxOQAAACBrgceIWXbgY2l03WOaKkn4B8vh
              QJcXDcVGXnZjev+WZAAAAEAwUQIBATAFBgMrZXAEIgQgKges9969nmD5i0SiRVyw
              xGuBx4hZduBjaXTdY5oqSfgHy+FAlxcNxUZedmN6/5ZkAAAAAAECAwQF
              -----END OPENSSH PRIVATE KEY-----

            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: "api/build"
            REMOTE_HOST: ec2-35-155-214-56.us-west-2.compute.amazonaws.com
            REMOTE_USER: ec2-user
            TARGET: ~/api
            EXCLUDE: "/app/"
            SCRIPT_AFTER: |
              sudo pm2 delete all && sudo npm run pm2 --prefix ~/api

