name: Push-to-EC2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Buid the application
      run: echo "Hello"

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key.cer && chmod 600 private_key.cer
          ssh -o StrictHostKeyChecking=no -i private_key.cer ec2-user@ec2-35-155-214-56.us-west-2.compute.amazonaws.com '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd ~/stylify &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
          '
