name: Push-to-EC2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Buid the application
      run: echo "Hello"

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2

        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: "api/"
            REMOTE_HOST: ec2-35-155-214-56.us-west-2.compute.amazonaws.com
            REMOTE_USER: ec2-user
            TARGET: ~/stylify
            EXCLUDE: "/app/"
            SCRIPT_AFTER: |
              whoami
              ls -al
              echo $RSYNC_STDOUT

