name: Push-to-EC2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Buid API
      run: |
        npm i --prefix api &&
        npm run build --prefix api &&
        cp -r api/node_modules api/build &&
        cp -r api/prisma api/build &&
        ls api

    - name: Zip artifact for deployment
      run: zip release.zip ./api/build -r

    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build

      # - name: Unzip artifact for deployment
      #   run: unzip release.zip

      - name: Deploy in EC2
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: |
              ${{ secrets.EC2_SSH_PRIVATE_KEY }}

            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: "release.zip"
            REMOTE_HOST: ec2-35-155-214-56.us-west-2.compute.amazonaws.com
            REMOTE_USER: ec2-user
            TARGET: ~/api
            EXCLUDE: "/app/"
            SCRIPT_BEFORE: |
              sudo rm -rf ~/api/*
            SCRIPT_AFTER: |
              at now + 1 minute -f ~/deploy.sh


